### ISSUE TITLE
Easily init new Architect projects

### ISSUE THREAD

**Issue by leeroybrun** [c9/architect#33]
Hello,

Just to let you know that I have created a simple module to easily create base structure and files for new architect projects.

https://github.com/leeroybrun/architect-init

Feedback is always welcome !

**Comment by stephengardner** [comment]
hey @leeroybrun, thanks for creating that!  I have another initialization case for single modules I was wondering if you thought it would be worthwhile to check out. 

https://github.com/c9/architect/issues/47

Cheers
