### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by shaharmor** [c9/architect#48]
Hey,

Whats the status of this project? Are you guys still using it in production?

**Comment by nightwing** [comment]
Yes, we use slightly modified version which can be found at https://github.com/c9/core/blob/master/node_modules/architect/architect.js

**Comment by shaharmor** [comment]
Why not keep this one up to date? Looks like a very promising package

**Comment by LukeCarrier** [comment]
:+1: it seems odd to duplicate the module when there's already a lot (> 500) stars on this repository. At the very least, you should make it clear in the README that you're also versioning this code elsewhere.

**Comment by nightwing** [comment]
This repo got a bit behind, because the changes in c9/core likely need some reworking in order to be merged into master, and we didn't have time to set up syncing script yet. We'll do that eventually but if there is some change in c9/core version you want to use now, we can give that higher priority

**Comment by naoisegolden** [comment]
+1 please update this repo

**Comment by stavros-zavrakas** [comment]
I am using this module as well. It will be nice if it can be updated with the latest version.

**Comment by jeremieca** [comment]
+1 too

**Comment by impcyber** [comment]
+1 it will be nice to work with latest version

**Comment by johnf** [comment]
This can probably be closed a a sync was performed recently. Infact this is ahead of c9/core after the most recent commit.
