### ISSUE TITLE
Does this support events/filters?

### ISSUE THREAD

**Issue by jhyland87** [c9/architect#50]
Im looking for a plugin system I can use that will allow users to add functionality, and take advantage of events/filters that already exist in the application. I can see that _Architect_ allows you to install plugins that add functionality that can be used by the system and other plugins, but does it allow you to add/apply filters? (WPs [add_filter()](https://codex.wordpress.org/Function_Reference/add_filter) and [apply_filters()](https://codex.wordpress.org/Function_Reference/apply_filters) for example), or add/apply actions/events?

**Comment by nightwing** [comment]
No, as you can use node builtin EventEmitter in a similar way.
But if you want to fully copy WP api, porting https://core.trac.wordpress.org/browser/tags/4.4.1/src/wp-includes/plugin.php#L199 to js should be easy.
