### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by johnf** [c9/architect#57]
Looks like this was synced with cloud9 version recently. Could a new release to npm happen? Thanks!

**Comment by mattpardee** [comment]
ping @sergi @fjakobs @lennartcl @creationix

**Comment by creationix** [comment]
Sounds good, anyone still at c9 have push access to npm?

**Comment by mattpardee** [comment]
@nightwing you merged the last PR, do you?

**Comment by sergi** [comment]
Looks like I could do it. What actually has to happen? Where is the new version?

**Comment by nightwing** [comment]
@sergi version from master needs to be published to npm, i do not have access to it https://www.npmjs.com/package/architect/access

**Comment by mattpardee** [comment]
I think you can just clone this down and 'npm publish' @sergi

**Comment by lennartcl** [comment]
Alright, just `npm publish`d this. Thanks for poking us @johnf @mattpardee!
